name: update maintainer data cronjob

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 20 1 * *"

jobs:
  updateProjectData:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: BSFishy/pip-action@v1
        with:
          requirements: project/requirements.txt
      - run: |
          ./project/bin/get_maintainer_data
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Update maintainer data
          signoff: true
